BacklogBundle\Entity\Item:
    type: entity
    table: backlog_items
    repositoryClass: BacklogBundle\Repository\ItemRepository
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
        estimate:
            type: smallint
            nullable: TRUE
        priority:
            type: smallint
            nullable: TRUE
        status:
            type: string
            length: 20
            nullable: TRUE

    manyToOne:
        creator:
            targetEntity: BacklogBundle\Entity\User
            joinColumn:
                name: creator_id
                referencedColumnName: id
        sprint:
            targetEntity: BacklogBundle\Entity\Sprint
            inversedBy: items
            joinColumn:
                name: sprint_id
                referencedColumnName: id