BacklogBundle\Entity\Item:
    type: entity
    table: backlog_items
    repositoryClass: BacklogBundle\Repository\ItemRepository
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
        estimate:
            type: smallint
            nullable: TRUE
        priority:
            type: smallint
            nullable: TRUE
        status:
            type: string
            length: 20
            nullable: TRUE
        imageName:
            type: string
            nullable: TRUE

    oneToMany:
        subItems:
            targetEntity: BacklogBundle\Entity\SubItem
            mappedBy: parentItem
    manyToOne:
        creator:
            targetEntity: BacklogBundle\Entity\User
            joinColumn:
                name: creator_id
                referencedColumnName: id
        sprint:
            targetEntity: BacklogBundle\Entity\Sprint
            inversedBy: items
            joinColumn:
                name: sprint_id
                referencedColumnName: id
        epic:
            targetEntity: BacklogBundle\Entity\Epic
            joinColumn:
                name: epic_id
                referencedColumnName: id
    manyToMany:
        labels:
            targetEntity: BacklogBundle\Entity\Label
            cascade: [persist]
            joinTable:
                name: item_labels
                joinColumns:
                    item_id:
                      referencedColumnName: id
                inverseJoinColumns:
                    label_id:
                      referencedColumnName: id