BacklogBundle\Entity\Sprint:
    type: entity
    table: sprints
    id:
            id:
                type: integer
                generator: {strategy: AUTO}
    fields:
        duration:
           type: string
           length: 30
        startDate:
            type: datetime
            nullable: TRUE
        isStarted:
            type: boolean
    oneToMany:
        items:
            targetEntity: BacklogBundle\Entity\Item
            mappedBy: sprint
    manyToOne:
            creator:
                targetEntity: BacklogBundle\Entity\User
                joinColumn:
                    name: creator_id
                    referencedColumnName: id